### ISSUE TITLE
Instead of mariadb, postgresql is better.

### ISSUE THREAD

**Issue by krotesk** [Trikke76/Zabbix-Book#9]
Chapter [Installing the Zabbix server for PostgreSQL](https://github.com/Trikke76/Zabbix-Book/blob/main/docs/installation/installing-zabbix.md#installing-the-zabbix-server-for-postgresql)

> In our case the config will look like this:
```
# vi /etc/zabbix/zabbix_server.conf

DBHost=<ip or dns of your MariaDB server>
DBName=zabbix
DBSchema=zabbix_server
DBUser=zabbix-srv
DBPassword=<your super secret password>
DBPort=5432
```
PostgreSQL instead of mariadb

and 
a little further

> The only thing that needs to be done is remove the # in front of the line '# Include=/usr/local/etc/zabbix_server.conf.d/*.conf' and make sure the path exists with a customized config file of your **won** that is readable by the user zabbix.

won -> win?

**Comment by Trikke76** [comment]
hi,

thx i fixed the typo and did some rewrite of certain sentences
